import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Listen for the 'push' event
self.addEventListener('push', (event) => {
    if (event.data) {
        try {
            const payload = event.data.json();
            
            const options = {
                body: payload.message,
                icon: '/pwa-192x192.svg',
                badge: '/pwa-192x192.svg',
                vibrate: [100, 50, 100],
                data: {
                    url: payload.url || '/',
                    id: payload.id
                },
                actions: [
                    { action: 'open', title: 'View Details' },
                    { action: 'close', title: 'Close' }
                ]
            };

            event.waitUntil(
                self.registration.showNotification(payload.title, options)
            );
        } catch (e) {
            console.error('Push payload parsing failed:', e);
            // Fallback for simple text messages
            event.waitUntil(
                self.registration.showNotification('New Notification', {
                    body: event.data.text(),
                    icon: '/pwa-192x192.svg'
                })
            );
        }
    }
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    if (event.action === 'close') return;

    const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window open with this URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
